//
// Created by terje on 01.05.2022.
//

#ifndef CPPVALIDINTCHECKER_GOTOTHISLINEINCONSOLE_H
#define CPPVALIDINTCHECKER_GOTOTHISLINEINCONSOLE_H

void gotoLineInConsole(int column, int row);
#endif //CPPVALIDINTCHECKER_GOTOTHISLINEINCONSOLE_H
