//
// Created by terje on 01.05.2022.
//

#ifndef CPPVALIDINTCHECKER_MYCOUNTDOWNTOEXIT_H
#define CPPVALIDINTCHECKER_MYCOUNTDOWNTOEXIT_H

void CountDown(int secondsCountDown);
#endif //CPPVALIDINTCHECKER_MYCOUNTDOWNTOEXIT_H
